import type { GridRow } from "@/components/app/DataGrid";

export function exportToExcel(rows: GridRow[], filename = "bank_statement") {
  import("xlsx").then((XLSX) => {
    const wsData = [
      ["Date", "Description", "Category", "Debit", "Credit", "Balance"],
      ...rows.map((r) => [
        r.date,
        r.description,
        r.category,
        r.debit,
        r.credit,
        r.balance,
      ]),
    ];
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    ws["!cols"] = [
      { wch: 12 },
      { wch: 30 },
      { wch: 15 },
      { wch: 12 },
      { wch: 12 },
      { wch: 14 },
    ];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Statement");
    XLSX.writeFile(wb, `${filename}.xlsx`);
  });
}

export function exportToQuickBooksCSV(
  rows: GridRow[],
  filename = "bank_statement_qb"
) {
  const headers = ["Date", "Description", "Amount"];
  const csvRows = rows.map((r) => {
    const amount = r.credit
      ? r.credit.replace(/[^0-9.-]/g, "")
      : r.debit
      ? `-${r.debit.replace(/[^0-9.-]/g, "")}`
      : "0";
    return [r.date, `"${r.description.replace(/"/g, '""')}"`, amount];
  });

  const csv = [headers.join(","), ...csvRows.map((r) => r.join(","))].join(
    "\n"
  );
  downloadBlob(csv, `${filename}.csv`, "text/csv;charset=utf-8;");
}

export function exportToWord(rows: GridRow[], filename = "bank_statement") {
  const tableRows = rows
    .map(
      (r) =>
        `<tr>
          <td>${r.date}</td>
          <td>${r.description}</td>
          <td>${r.category}</td>
          <td style="text-align:right">${r.debit}</td>
          <td style="text-align:right">${r.credit}</td>
          <td style="text-align:right">${r.balance}</td>
        </tr>`
    )
    .join("");

  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8"><title>Bank Statement</title>
    <style>
      body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
      table { border-collapse: collapse; width: 100%; margin-top: 12pt; }
      th, td { border: 1px solid #D4D4D4; padding: 6pt 10pt; }
      th { background: #F1F5F9; font-weight: bold; text-align: left; font-size: 10pt; color: #334155; }
      td { font-size: 10pt; color: #1E293B; }
      h1 { font-size: 16pt; color: #0F172A; margin-bottom: 4pt; }
      p { font-size: 9pt; color: #64748B; }
    </style>
    </head>
    <body>
      <h1>Bank Statement Extract</h1>
      <p>Generated by CleanStmt &mdash; ${rows.length} rows, no merged cells</p>
      <table>
        <thead>
          <tr>
            <th>Date</th><th>Description</th><th>Category</th>
            <th>Debit</th><th>Credit</th><th>Balance</th>
          </tr>
        </thead>
        <tbody>${tableRows}</tbody>
      </table>
    </body></html>`;

  downloadBlob(html, `${filename}.doc`, "application/msword");
}

export function copyToClipboard(rows: GridRow[]): Promise<void> {
  const header = "Date\tDescription\tCategory\tDebit\tCredit\tBalance";
  const body = rows
    .map(
      (r) =>
        `${r.date}\t${r.description}\t${r.category}\t${r.debit}\t${r.credit}\t${r.balance}`
    )
    .join("\n");
  return navigator.clipboard.writeText(`${header}\n${body}`);
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
